## caption_functions.R

# Load packages ---------------------------
library(stringr)

# Create caption of coral cover by year plot ---------------------------
generate_coral_cover_year_caption <- function(input) {
    selected_localities <- paste(input$coral_cover_year_choose_locality, collapse = ", ")
    selected_years <- paste(input$coral_cover_year_choose_year, collapse = ", ")
    if (input$coral_cover_year_consolidate_year) {
        caption_text <- paste0(
            "Figure Caption: Plot of percent coral cover across localities (", selected_localities,
            ") for years (", selected_years, ") at Turneffe Atoll. Generated by University of Belize Environmental Research Institute."
        )
    } else {
        caption_text <- paste0(
            "Plot of percent coral cover within localities (", selected_localities,
            ") and across years (", selected_years, ") at Turneffe Atoll. Generated by University of Belize Environmental Research Institute."
        )
    }
    str_wrap(caption_text, width = 150)
}

# Create caption of coral cover by species plot ---------------------------
generate_coral_cover_species_caption <- function(input) {
    if (input$coral_cover_species_select_species != "All") {
        selected_species <- input$coral_cover_species_select_species
    } else {
        selected_species <- "most common coral species"
    }
    selected_localities <- paste(input$coral_cover_species_choose_locality, collapse = ", ")
    selected_years <- paste(input$coral_cover_species_choose_year, collapse = ", ")
    caption_text <- paste0(
        "Figure Caption: Plot of percent coral cover by coral species. Data for localities (", selected_localities,
        ") and for years (", selected_years, ") for ", selected_species, " at Turneffe Atoll. Generated by University of Belize Environmental Research Institute."
    )
    str_wrap(caption_text, width = 150)
}
